name: Rust

on:
  push:
    branches: [ master, cicd ]
  pull_request:
    branches: [ master, cicd ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        gay: ['yes']
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Generate Docs
      run: cargo doc --verbose
